In [1]:
import numpy as np
A = np.array([1, 2, 3])
B = 10 # B = [10, 10, 10]
A + B

array([11, 12, 13])

In [2]:
C = np.array([[10, 20, 30], [40, 50, 60]])
A + C # A = [[1, 2, 3], [1, 2, 3]]

array([[11, 22, 33],
       [41, 52, 63]])

In [3]:
D = np.array([10, 20])
A + D

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [4]:
W = np.array([0, 1, 2, 3])
X = np.array([1, 2, 3])
W + X

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [5]:
W[:, np.newaxis] + X

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [6]:
'''
上面的運算方式是：
array([[0 + 1, 0 + 2, 0 + 3],
       [1 + 1, 1 + 2, 1 + 3],
       [2 + 1, 2 + 2, 2 + 3],
       [3 + 1, 3 + 2, 3 + 3]])
'''

'\n上面的運算方式是：\narray([[0 + 1, 0 + 2, 0 + 3],\n       [1 + 1, 1 + 2, 1 + 3],\n       [2 + 1, 2 + 2, 2 + 3],\n       [3 + 1, 3 + 2, 3 + 3]])\n'