In [1]:
import numpy as np
A = np.array([1, 2, 3])
B = A # 令B參照A所參照的物件，不會建立新的物件
B is A # A和B是參照相同的陣列物件

True

In [2]:
B[0] = 7 # 將B的第一個元素變更為7
A # A的第一個元素亦變成7

array([7, 2, 3])

In [3]:
A = np.array([1, 2, 3])
C = A.view() # 建立新的陣列物件C並共享A的資料
C is A # C和A是不同的陣列物件

False

In [4]:
C.base is A # 透過C的base屬性判斷其基底物件是否為A

True

In [5]:
C[0] = 7 # 將C的第一個元素變更為7
C # C的第一個元素變成7

array([7, 2, 3])

In [6]:
A # A的第一個元素亦變成7

array([7, 2, 3])

In [7]:
A = np.array([1, 2, 3])
D = A.copy() # 建立新的陣列物件D並複製A的資料
D is A # D和A是不同的陣列物件

False

In [8]:
D.base is A # D是A的複本，擁有獨立的資料

False

In [9]:
D[0] = 7 # 將D的第一個元素變更為7
D # D的第一個元素變成7

array([7, 2, 3])

In [10]:
A # A的第一個元素仍保持不變

array([1, 2, 3])