In [1]:
import numpy as np
A = np.array([1, 2, 3])
B = np.square(A)
B

array([1, 4, 9])

In [2]:
help(np.square)

Help on ufunc:

square = <ufunc 'square'>
    square(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Return the element-wise square of the input.
    
    Parameters
    ----------
    x : array_like
        Input data.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``out=None``

In [3]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(4, 2)
B = np.ones((4, 2))
C = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

In [4]:
A.ndim

2

In [5]:
A.shape

(4, 2)

In [6]:
A.shape[0]

4

In [7]:
A.shape[1]

2

In [8]:
A.size

8

In [9]:
np.vstack((A, B))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
D = A.reshape(2, 4)
D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
np.transpose(A)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [12]:
A + B

array([[2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [13]:
A - B

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.]])

In [14]:
A @ C

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])