In [1]:
import numpy as np
np.sin(np.array([0, 30, 45]) * np.pi / 180.)

array([0.        , 0.5       , 0.70710678])

In [2]:
np.cos(np.array([30, 45, 60]) * np.pi / 180.)

array([0.8660254 , 0.70710678, 0.5       ])

In [3]:
np.tan(np.array([30, 45, 60]) * np.pi / 180.)

array([0.57735027, 1.        , 1.73205081])

In [4]:
np.sqrt(3) + np.cbrt(5)

3.4420267542455742

In [5]:
A = np.array([1, 1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8])
np.sum(A)

2.7178571428571425

In [6]:
np.prod(A)

2.4801587301587298e-05

In [7]:
x = np.log2(3)
np.power(2, x) + np.power(4, -x)

3.111111111111111

In [8]:
np.gcd(([1, 8, 10, 15, 20, 50, 210, 980]), 100)

array([ 1,  4, 10,  5, 20, 50, 10, 20])

In [9]:
np.sort(np.array([[5, 3, 2, 6], [1, 7, 8, 4]]))

array([[2, 3, 5, 6],
       [1, 4, 7, 8]])

In [10]:
np.round_(-5.4789, 2)

-5.48

In [11]:
np.rint(-5.4789)

-5.0

In [12]:
np.floor(-5.4789)

-6.0

In [13]:
np.ceil(-5.4789)

-5.0

In [14]:
np.trunc(-5.4789)

-5.0

In [15]:
U = np.array([0, 2, 4])
V = np.array([1, 3, 5])
np.inner(U, V)

26

In [16]:
np.cross(U, V)

array([-2,  4, -2])

In [17]:
np.outer(U, V)

array([[ 0,  0,  0],
       [ 2,  6, 10],
       [ 4, 12, 20]])