In [1]:
import numpy as np

In [2]:
score = np.array([[80, 75, 88, 80, 78], [88, 86, 90, 95, 86], [92, 85, 92, 98, 90], [81, 88, 80, 82, 85], [75, 80, 78, 80, 70]])
np.mean(score, axis = 1) # 算術平均

array([80.2, 89. , 91.4, 83.2, 76.6])

In [3]:
np.average(score, axis = 1, weights = [0.5, 0.2, 0.1, 0.1, 0.1]) # 加權平均

array([79.6, 88.3, 91. , 82.8, 76.3])

In [4]:
np.median(score, axis = 1) # 中位數

array([80., 88., 92., 82., 78.])

In [5]:
np.std(score, axis = 1) # 標準差

array([4.30813185, 3.34664011, 4.1761226 , 2.92574777, 3.77359245])

In [6]:
np.var(score, axis = 1) # 變異數

array([18.56, 11.2 , 17.44,  8.56, 14.24])