In [1]:
import numpy as np

In [2]:
np.sin(30 * np.pi / 180)

0.49999999999999994

In [3]:
np.round([1.23, 0.78])

array([1., 1.])

In [4]:
np.round([1.23, 0.78], 1)

array([1.2, 0.8])

In [5]:
np.rint([1.1, 1.6, 1.8])

array([1., 2., 2.])

In [6]:
np.floor([-1.1, 1.6, 5.78])

array([-2.,  1.,  5.])

In [7]:
np.ceil([-1.1, 1.6, 5.78])

array([-1.,  2.,  6.])

In [8]:
np.trunc([-1.1, 1.6, 5.78])

array([-1.,  1.,  5.])

In [9]:
np.prod(np.array([[1, 2], [3, 4]]))

24

In [10]:
np.prod(np.array([[1, 2], [3, 4]]), 1)

array([ 2, 12])

In [11]:
np.cumprod(np.array([[1, 2], [3, 4]]))

array([ 1,  2,  6, 24])

In [12]:
np.sum(np.array([[1, 2], [3, 4]]))

10

In [13]:
np.sum(np.array([[1, 2], [3, 4]]), 1)

array([3, 7])

In [14]:
np.cumsum(np.array([[1, 2], [3, 4]]))

array([ 1,  3,  6, 10])

In [15]:
np.diff(np.array([1, 2, 4, 7]))

array([1, 2, 3])

In [16]:
np.exp([1, 2])

array([2.71828183, 7.3890561 ])

In [17]:
np.exp2([1, 2])

array([2., 4.])

In [18]:
np.log([1, 2])

array([0.        , 0.69314718])

In [19]:
np.log2([1, 2])

array([0., 1.])

In [20]:
np.log10([1, 2])

array([0.     , 0.30103])

In [21]:
np.add([4, 6], [2, 4])

array([ 6, 10])

In [22]:
np.subtract([4, 6], [2, 4])

array([2, 2])

In [23]:
np.multiply([4, 6], [2, 4])

array([ 8, 24])

In [24]:
np.divide([4, 6], [2, 4])

array([2. , 1.5])

In [25]:
np.power([4, 6], [2, 4])

array([  16, 1296])

In [26]:
np.mod([-3, -2, -1, 1, 2], 2)

array([1, 0, 1, 1, 0], dtype=int32)

In [27]:
np.mod([-3, -2, -1, 1, 2], -2)

array([-1,  0, -1, -1,  0], dtype=int32)

In [28]:
np.fmod([-3, -2, -1, 1, 2], 2)

array([-1,  0, -1,  1,  0], dtype=int32)

In [29]:
np.fmod([-3, -2, -1, 1, 2], -2)

array([-1,  0, -1,  1,  0], dtype=int32)

In [30]:
np.divmod(np.arange(5), 3)

(array([0, 0, 0, 1, 1], dtype=int32), array([0, 1, 2, 0, 1], dtype=int32))

In [31]:
np.negative([-3, -2, -1, 1, 2])

array([ 3,  2,  1, -1, -2])

In [32]:
np.sign([-5., 4.5, 0])

array([-1.,  1.,  0.])

In [33]:
np.absolute([-5., 4.5, 0])

array([5. , 4.5, 0. ])

In [34]:
np.sqrt([1, 2])

array([1.        , 1.41421356])

In [35]:
np.cbrt([1, 8])

array([1., 2.])

In [36]:
np.square([1, 8])

array([ 1, 64])

In [37]:
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

In [38]:
np.minimum([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [39]:
np.gcd([1, 2, 3, 4], 20)

array([1, 2, 1, 4])

In [40]:
np.isinf([np.nan, 1, np.inf])

array([False, False,  True])

In [41]:
np.isfinite([np.nan, 1, np.inf])

array([False,  True, False])

In [42]:
np.isnan([np.nan, 1, np.inf])

array([ True, False, False])

In [43]:
np.max([0.5, 0.7, 0.2, 1.5])

1.5

In [44]:
np.min([0.5, 0.7, 0.2, 1.5])

0.2

In [45]:
np.sort([2, 1, 5, 4, 3, 7, 6])

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
np.sort(np.array([[1, 4, 2], [3, 7, 5]]))

array([[1, 2, 4],
       [3, 5, 7]])