In [1]:
import numpy as np

In [2]:
np.random.rand(3)

array([0.7182057 , 0.2550611 , 0.72723969])

In [3]:
np.random.randn(3)

array([-0.80479091,  1.13368254,  0.35116028])

In [4]:
np.random.randint(5, 10, size = 3)

array([9, 7, 5])

In [5]:
np.random.random(2)

array([0.23140397, 0.51969459])

In [6]:
np.random.choice(5, 3)

array([2, 2, 3])

In [7]:
A = np.array([0, 1, 2, 3, 4])
np.random.shuffle(A)
A

array([3, 0, 2, 4, 1])

In [8]:
np.random.permutation(np.array([0, 1, 2, 3, 4]))

array([2, 3, 0, 1, 4])

In [9]:
np.random.seed(100)
np.random.randn(2)

array([-1.74976547,  0.3426804 ])