In [1]:
import numpy as np

In [2]:
np.loadtxt("C:\\Users\\chen_\\Desktop\\MyProject\\Python_Project\\Python程式設計（第三版）\\Chapter12\\Data.txt", delimiter = ',') # 指定分隔字元為逗號

array([[ 15., 160.,  48.],
       [ 14., 175.,  66.],
       [ 15., 153.,  50.],
       [ 15., 162.,  44.]])

In [3]:
np.loadtxt("C:\\Users\\chen_\\Desktop\\MyProject\\Python_Project\\Python程式設計（第三版）\\Chapter12\\Data.txt", delimiter = ',', skiprows = 2) # 忽略前2列

array([[ 15., 153.,  50.],
       [ 15., 162.,  44.]])

In [4]:
np.loadtxt("C:\\Users\\chen_\\Desktop\\MyProject\\Python_Project\\Python程式設計（第三版）\\Chapter12\\Data.txt", delimiter = ',', usecols = (0, 2)) # 讀取第1、3行

array([[15., 48.],
       [14., 66.],
       [15., 50.],
       [15., 44.]])

In [5]:
x = y = z = np.arange(0, 5, 1)
np.savetxt("C:\\Users\\chen_\\Desktop\\MyProject\\Python_Project\\Python程式設計（第三版）\\Chapter12\\Test.txt", (x, y ,z), delimiter = ',', fmt = "%1.2f")