In [1]:
import numpy as np
A = np.array([10, 20, 30])

In [2]:
print(A[0], A[1], A[2])

10 20 30


In [3]:
import numpy as np # 匯入Numpy並設定別名為np
A = np.array([1, 3, 5, 7, 9]) # 建立包含5個元素的一維陣列A
A

array([1, 3, 5, 7, 9])

In [4]:
print(A) # 印出陣列A

[1 3 5 7 9]


In [5]:
type(A) # 陣列A的型別

numpy.ndarray

In [6]:
A.ndim # 陣列A的維度

1

In [7]:
A.shape # 陣列A的形狀（5表示第一維的元素個數）

(5,)

In [8]:
A.size # 陣列A的元素個數

5

In [9]:
A.dtype # 陣列A的元素型別

dtype('int32')

In [10]:
A.itemsize # 陣列A的元素大小

4

In [11]:
A[0] # 陣列A的第一個元素

1

In [12]:
A[2:] # 陣列A中索引2和之後的元素

array([5, 7, 9])

In [13]:
A[:2] # 陣列A中索引2之前的元素（不含索引2）

array([1, 3])

In [14]:
A[2:5] # 陣列A中索引2到4的元素（不含索引5）

array([5, 7, 9])

In [15]:
A[-2] # 陣列A的倒數第二個元素

7

In [16]:
A = np.array([1, 6, 8, 3, 9]) # 建立包含5個整數的陣列A
A.dtype # 陣列A的元素型別

dtype('int32')

In [17]:
print(A) # 印出陣列A

[1 6 8 3 9]


In [18]:
A = np.array([1, 6, 8, 3, 9], dtype = np.int16)
A.dtype # 陣列A的元素型別

dtype('int16')

In [19]:
B = np.array([1.2, -3.5, 7.6]) # 建立包含3個浮點數的陣列B
B.dtype # 陣列B的元素型別

dtype('float64')

In [20]:
C = np.array(["cat", "dog", "pig"]) # 建立包含3個字串的陣列C
C.dtype # 陣列C的元素型別

dtype('<U3')

In [21]:
np.zeros(10) # 建立包含10個0的一維陣列

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10) # 建立包含10個1的一維陣列

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.empty(3) # 建立包含3個隨機值的一維陣列

array([1.22722042e-311, 0.00000000e+000, 2.07535611e+026])

In [24]:
# 建立起始值為1、終止值為10（不含10）、間隔值為3、型別為int32的數列
np.arange(start = 1, stop = 10, step = 3, dtype = int)

array([1, 4, 7])

In [25]:
# 建立起始值為0、終止值為5（不含5）、間隔值為1、型別為int32的數列
np.arange(5, dtype = int)

array([0, 1, 2, 3, 4])

In [26]:
# 建立起始值為0、終止值為2（不含2）、間隔值為0.3的數列
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [27]:
np.linspace(0, 2, 9) # 建立0到2之間9個平均分佈的數值

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
A = np.array([10, 20, 30, 40, 50])
B = np.array([1, 2, 3, 4, 5])

In [29]:
A * 2

array([ 20,  40,  60,  80, 100])

In [30]:
A ** 2

array([ 100,  400,  900, 1600, 2500])

In [31]:
A < 35

array([ True,  True,  True, False, False])

In [32]:
A + B

array([11, 22, 33, 44, 55])

In [33]:
A - B

array([ 9, 18, 27, 36, 45])

In [34]:
A * B

array([ 10,  40,  90, 160, 250])

In [35]:
A / B

array([10., 10., 10., 10., 10.])

In [36]:
A > B

array([ True,  True,  True,  True,  True])

In [37]:
A[0] = 100
print(A)

[100  20  30  40  50]


In [38]:
A[[0, 1]] = 70
print(A)

[70 70 30 40 50]


In [39]:
A = np.array([10, 20, 30, 40, 50])
C = np.insert(A, 1, 100)
C

array([ 10, 100,  20,  30,  40,  50])

In [40]:
D = np.insert(A, [1, 3], 7)
D

array([10,  7, 20, 30,  7, 40, 50])

In [41]:
A = np.array([10, 20, 30, 40, 50])
C = np.delete(A, 2)
C

array([10, 20, 40, 50])

In [42]:
D = np.delete(A, [1, 3])
D

array([10, 30, 50])

In [43]:
A = np.array([1, 2, 3])
B = np.array([4, 5])
C = np.concatenate((A, B))
C

array([1, 2, 3, 4, 5])

In [44]:
D = np.concatenate((A, [10, 20]))
D

array([ 1,  2,  3, 10, 20])

In [45]:
U = np.array([1, 2, 3]) # 建立向量U
V = np.array([1, 0, 1]) # 建立向量V

In [46]:
np.inner(U, V) # 計算向量內積，亦可寫成np.dot(U, V)

4

In [47]:
np.cross(U, V) # 計算向量叉積

array([ 2,  2, -2])

In [48]:
np.outer(U, V) # 計算向量外積

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3]])