In [1]:
import numpy as np
grades = np.array([[95, 100, 100], [86, 90, 75], [98, 98, 96], [78, 90, 80], [70, 68, 72]])
print(grades) # 印出二維陣列

[[ 95 100 100]
 [ 86  90  75]
 [ 98  98  96]
 [ 78  90  80]
 [ 70  68  72]]


In [2]:
grades[0, ] # 學生1的三科分數，亦可寫成grades[0]

array([ 95, 100, 100])

In [3]:
grades[0, 0] # 學生1的第1科分數（國文），亦可寫成grades[0][0]

95

In [4]:
grades[1, 2] # 學生2的第3科分數（數學），亦可寫成grades[1][2]

75

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(4, 3)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
np.zeros((3, 5)) # 建立3*5、包含0的二維陣列

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((3, 5)) # 建立3*5、包含1的二維陣列

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.empty((2, 3)) # 建立2*3、包含隨機值的二維陣列

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313]])

In [10]:
np.arange(15).reshape(3, 5) # 建立3*5的二維陣列

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
np.linspace(0, 2, 9).reshape(3, 3) # 建立3*3的二維陣列

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

In [12]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(4, 3)
print(A) # 印出二維陣列A

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
A.ndim # 陣列A的維度

2

In [14]:
A.shape # 陣列A的形狀（此例為4列3行）

(4, 3)

In [15]:
A.shape[0] # 陣列A的列維度（此例為4列）

4

In [16]:
A.shape[1] # 陣列A的行維度（此例為3行）

3

In [17]:
A.size # 陣列A的元素個數

12

In [18]:
A.dtype # 陣列A的型別

dtype('int32')

In [19]:
A.itemsize # 陣列A的元素大小

4

In [20]:
A[0, 0] # 第1行第1列的元素，亦可寫成A[0][0]

1

In [21]:
A[0, :] # 第1列的元素，亦可寫成A[0, ]或A[0]

array([1, 2, 3])

In [22]:
A[:, 0] # 第1行的元素

array([ 1,  4,  7, 10])

In [23]:
A[1:3, 0] # 元素A[1, 0]和A[2, 0]（不含索引3）

array([4, 7])

In [24]:
A[2:] # 第3列和之後的元素

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
A[:2] # 第3列之前的元素（不含第3列）

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
A[-1] # 最後一行的元素

array([10, 11, 12])

In [27]:
for i in A: # 針對陣列A進行迭代運算
    print(i + 10)

[11 12 13]
[14 15 16]
[17 18 19]
[20 21 22]


In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 2], [1, 1]])

In [29]:
A * 2 # 陣列A乘以2

array([[2, 4],
       [6, 8]])

In [30]:
A > 2 # 陣列A是否大於2

array([[False, False],
       [ True,  True]])

In [31]:
A + B # 陣列A加上陣列B

array([[3, 4],
       [4, 5]])

In [32]:
A - B # 陣列A減去陣列B

array([[-1,  0],
       [ 2,  3]])

In [33]:
A * B # 陣列A乘以陣列B

array([[2, 4],
       [3, 4]])

In [34]:
A / B # 陣列A除以陣列B

array([[0.5, 1. ],
       [3. , 4. ]])

In [35]:
A = np.array([[1, 2], [3, 4]])
A[0, 0] = 7 # 將第1列第1行的元素變更為7
print(A) # 印出陣列A（第1行第1列的元素被變更為7）

[[7 2]
 [3 4]]


In [36]:
A = np.array([[0, 1, 2], [3, 4, 5]])
A.ravel() # 傳回將陣列A轉換成一維陣列的新陣列

array([0, 1, 2, 3, 4, 5])

In [37]:
A.reshape(3, 2) # 傳回將陣列A轉換成3*2陣列的新陣列

array([[0, 1],
       [2, 3],
       [4, 5]])

In [38]:
A.resize(3, 2) # 將陣列A本身轉換成3*2陣列
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
A = np.arange(16).reshape(2, 8)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [40]:
np.hsplit(A, 4) # 將陣列A水平分割成4個子陣列

[array([[0, 1],
        [8, 9]]),
 array([[ 2,  3],
        [10, 11]]),
 array([[ 4,  5],
        [12, 13]]),
 array([[ 6,  7],
        [14, 15]])]

In [41]:
np.vsplit(A, 2) # 將陣列A垂直分割成2個子陣列

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]

In [42]:
A = np.array([[0, 1], [2, 3]])
B = np.array([[4, 5], [6, 7]])
C = np.array([8, 9])

In [43]:
np.hstack((A, B)) # 將陣列A和陣列B水平堆疊

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [44]:
np.vstack((A, B)) # 將陣列A和陣列B垂直堆疊

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [45]:
np.column_stack((A, C)) # 將陣列C當作一行堆疊到陣列A

array([[0, 1, 8],
       [2, 3, 9]])

In [46]:
np.row_stack((A, C)) # 將陣列C當作一列堆疊到陣列A

array([[0, 1],
       [2, 3],
       [8, 9]])

In [47]:
A = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(A)

[[1 2 3]
 [4 5 6]]


In [48]:
B = np.transpose(A)
print(B)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
A = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(A)

[[1 2 3]
 [4 5 6]]


In [50]:
B = A + A
print(B)

[[ 2  4  6]
 [ 8 10 12]]


In [51]:
A = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
B = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(B)

[[1 2 3]
 [4 5 6]]


In [53]:
C = A @ B # 亦可寫成C = np.dot(A, B)
print(C)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
