1. 一維陣列操作

In [1]:
import numpy as np

In [2]:
A = np.array([0, 1, 2, 3, 4, 5]) # A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [3]:
print(A.ndim, A.shape, A.size, A.itemsize)

1 (6,) 6 4


In [4]:
A[0] = 9
A

array([9, 1, 2, 3, 4, 5])

In [5]:
B = np.delete(A, [0, 2])
B

array([1, 3, 4, 5])

In [6]:
C = np.concatenate((A, B))
C

array([9, 1, 2, 3, 4, 5, 1, 3, 4, 5])

In [7]:
C % 3

array([0, 1, 2, 0, 1, 2, 1, 0, 1, 2], dtype=int32)

In [8]:
A + B

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

2. 二維陣列操作

In [9]:
A = np.linspace(1, 11, 6).reshape(3, 2)
A

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

In [10]:
print(A.ndim, A.shape, A.size, A.itemsize)

2 (3, 2) 6 8


In [11]:
print(np.max(A), np.min(A))

11.0 1.0


In [12]:
B = np.transpose(A)
B

array([[ 1.,  5.,  9.],
       [ 3.,  7., 11.]])

In [13]:
C = A + A
C

array([[ 2.,  6.],
       [10., 14.],
       [18., 22.]])

In [14]:
D = A @ B
D

array([[ 10.,  26.,  42.],
       [ 26.,  74., 122.],
       [ 42., 122., 202.]])

In [15]:
E = A * 3
E

array([[ 3.,  9.],
       [15., 21.],
       [27., 33.]])

In [16]:
np.vstack((A, E))

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.],
       [ 3.,  9.],
       [15., 21.],
       [27., 33.]])

3. 使用NumPy計算下列題目的結果：

In [17]:
np.sin(30 * np.pi / 180.) + np.cos(60 * np.pi / 180.)

1.0

In [18]:
np.log2(np.sqrt(2))

0.5000000000000001

In [19]:
np.power(np.log(2), 3) + np.power(np.log(5), 3) + np.log(5) * np.log(8)

7.848668270144524

In [20]:
a, b, c = 2, 8, 6
Positive_Sol = (-b + np.sqrt(np.square(b) - 4 * a * c)) / (2 * a)
Negative_Sol = (-b - np.sqrt(np.square(b) - 4 * a * c)) / (2 * a)
print(Positive_Sol, Negative_Sol)

-1.0 -3.0


In [21]:
np.gcd([330, 70, 99, 63, 128, 36, 25], 3150)

array([30, 70,  9, 63,  2, 18, 25])

In [22]:
np.sort([330, 70, 99, 63, 128, 36, 25])

array([ 25,  36,  63,  70,  99, 128, 330])

In [23]:
np.round_([1.235, 2.7834, -99.9999, -100.1234], 2)

array([   1.24,    2.78, -100.  , -100.12])

4. 隨機取樣

In [24]:
np.random.random(5)

array([0.12407378, 0.80316939, 0.61904337, 0.12902824, 0.12941472])

In [25]:
np.random.randint(1, 10, size = 5) # 可自訂種子，例如：np.random.seed(10)

array([8, 9, 1, 3, 5])

In [26]:
np.random.triangular(-10, 0, 10, 5)

array([-0.6002995 ,  4.59564129,  2.32512032,  1.99093161,  0.84155962])

In [27]:
np.random.normal(0, 0.1, size = 5)

array([ 0.08265948,  0.07197614,  0.15073514,  0.01329054, -0.01270843])

In [28]:
np.random.poisson(10, size = 5)

array([17, 15, 14, 12, 11])

5. 體重統計分析

In [29]:
Weights = np.array([70, 68, 82, 65, 76, 71, 62, 74, 90])
print(np.amax(Weights), np.amin(Weights), np.mean(Weights), np.median(Weights), np.std(Weights), np.var(Weights))

90 62 73.11111111111111 71.0 8.184598604756843 66.98765432098766
